$axure.loadCurrentPage({
  "url":"dashboard.html",
  "generationDate":new Date(1406706485971.15),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2b7ee1c91003458c8a079dbd40f9d2f8",
    "type":"Axure:Page",
    "name":"Dashboard",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9b7fe40707c14a978bd8ced19af944f5",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"797b8b8e659a4cdc8ffd5b94d3b3bf88"},
{
          "id":"f148ba6665984e458e98ff9d49b485aa",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":177,
              "y":125},
            "size":{
              "width":848,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/dashboard______/u80_line.png"}},
{
          "id":"1b38e780a56040f3a0ff4da909d157a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":220,
              "y":86},
            "size":{
              "width":443,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09ab5ae40fda4e6fb8263494f8379c85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":220,
                  "y":86},
                "size":{
                  "width":443,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"716d64136acf4b1d98957636b1d68e9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":178,
              "y":130},
            "size":{
              "width":848,
              "height":750},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"223236c8d785428c8a8e2e8637ddbdc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":178,
                  "y":130},
                "size":{
                  "width":848,
                  "height":750},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard______/u74.png"}},
{
          "id":"401b56d4809e43d8b38215e245a99d2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":160},
            "size":{
              "width":791,
              "height":670},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9a6ed9c841745af9b2f9f3b0cede9b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":219,
                  "y":160},
                "size":{
                  "width":791,
                  "height":670},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u41.png"}},
{
          "id":"fa40a6d696784f32ad4e7a99f9f7156c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"center",
            "location":{
              "x":536,
              "y":190},
            "size":{
              "width":49,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"621646c101904cd9adfe184322bfd9a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "location":{
                  "x":536,
                  "y":190},
                "size":{
                  "width":49,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3004749a47d44c038cc6210f2a7914d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"center",
            "location":{
              "x":661,
              "y":190},
            "size":{
              "width":53,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d321b53422db4cd5b745d84b06789168",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "location":{
                  "x":661,
                  "y":190},
                "size":{
                  "width":53,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb0e4b3e0fc74802afc4f76166075817",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"center",
            "location":{
              "x":337,
              "y":190},
            "size":{
              "width":53,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1565f774f024612b9be8799f57a3144",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "location":{
                  "x":337,
                  "y":190},
                "size":{
                  "width":53,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4191d362a9c4aaf832e4e541ec7c506",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"center",
            "location":{
              "x":917,
              "y":190},
            "size":{
              "width":27,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcbda005d35446b2b954c798a81f53c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "location":{
                  "x":917,
                  "y":190},
                "size":{
                  "width":27,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dfacf743f20e4e3d8cec3983ffdbc870",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":213},
            "size":{
              "width":730,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/dashboard/u51_line.png"}},
{
          "id":"9a8260cd937043ce9daa7f47798ea39a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":534,
              "y":240},
            "size":{
              "width":54,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"410b02832c1a4570b168e974144bbea6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":534,
                  "y":240},
                "size":{
                  "width":54,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"749767d9a9234d8eba240b4100806d4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":673,
              "y":240},
            "size":{
              "width":30,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efe4cc1bbf0c405f9637ce59ac342a0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":673,
                  "y":240},
                "size":{
                  "width":30,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"234cdecdcd1f43f1a8e362435d3581a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":265,
              "y":240},
            "size":{
              "width":193,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0f55010de504c079a39210a7150cad7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":265,
                  "y":240},
                "size":{
                  "width":193,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81331379dac843dd8ff9dcb1d95e2916",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":249,
              "y":265},
            "size":{
              "width":730,
              "height":45},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db1d669e1d1442db891cb1cd7881742e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":249,
                  "y":265},
                "size":{
                  "width":730,
                  "height":45},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u58.png"}},
{
          "id":"3cf48c1f9ecf448c9313be18f13ed2ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":532,
              "y":282},
            "size":{
              "width":54,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6feeabee5c4e4488abcf17687d63ac3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":532,
                  "y":282},
                "size":{
                  "width":54,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36797feefdea4469967dfb32ad7d0a90",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":670,
              "y":282},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9dd59cb3bde445a93e94d56bf2ce6e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":670,
                  "y":282},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca74fc71fc7a468b8f7408af1c068cf1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":349},
            "size":{
              "width":730,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/dashboard/u64_line.png"}},
{
          "id":"af5acdf85a8e423688b2a33eb8553450",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":282,
              "y":280},
            "size":{
              "width":159,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ede6f7a59b0470fbce309cc39dd76fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":282,
                  "y":280},
                "size":{
                  "width":159,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a246395184b7489088c3c1d297b28c3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"center",
            "location":{
              "x":788,
              "y":190},
            "size":{
              "width":40,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a24bb366912c470f8c6528d819e148d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "location":{
                  "x":788,
                  "y":190},
                "size":{
                  "width":40,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"976e0b1b83744c599213fe978700309d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":790,
              "y":240},
            "size":{
              "width":29,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca3c27dcb0f64e788349aa849c56cc53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":790,
                  "y":240},
                "size":{
                  "width":29,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e95b7cc92b014d289efee9c932f4e1ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":794,
              "y":282},
            "size":{
              "width":22,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9db8e8dfb4741b98b384ae0cee15e79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":794,
                  "y":282},
                "size":{
                  "width":22,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bfadcd97ebc448079de489df3992b7a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":532,
              "y":323},
            "size":{
              "width":54,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2caec90220394a24914649703e421266",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":532,
                  "y":323},
                "size":{
                  "width":54,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c2c3e13f4734b52bd12f6ec8f311ee6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":670,
              "y":323},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce894ec4218b48019b54d6d79321f47c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":670,
                  "y":323},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3143efaae13142eca4b2ac35f4692490",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":274,
              "y":323},
            "size":{
              "width":177,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba05bd2c03844d839f105b2ad7f2badd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":274,
                  "y":323},
                "size":{
                  "width":177,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d7759c93c71e4483b88be31fe7d2c75a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":796,
              "y":323},
            "size":{
              "width":22,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af33c6afc8a04e29bb652d785d1a8e3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":796,
                  "y":323},
                "size":{
                  "width":22,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b363982fcff74e619d997d6b9a5fdf80",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":380},
            "size":{
              "width":279,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b169b5b21f6347b0bc34b8a19aa9cd48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":700,
                  "y":380},
                "size":{
                  "width":279,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard______/u148.png"}},
{
          "id":"ce768a52ca23478089ff934247bac62f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":901,
              "y":240},
            "size":{
              "width":59,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3847b31087143b583ead7ee888e8dac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":901,
                  "y":240},
                "size":{
                  "width":59,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a9e8d92963a4a38b130696f62679b8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":901,
              "y":282},
            "size":{
              "width":59,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1c84af07fa7499080a2a04d2b798537",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":901,
                  "y":282},
                "size":{
                  "width":59,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7376f30b1b8645cb9dd65687fc3db41b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":901,
              "y":323},
            "size":{
              "width":59,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a4b00ac5df84be3af8af2589810397e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":901,
                  "y":323},
                "size":{
                  "width":59,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"063b3e5511904a49807a1631fdfb9d7f",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"44edf4e907894980bb4b3423f2dd4166"}]}},
  "masters":{
    "797b8b8e659a4cdc8ffd5b94d3b3bf88":{
      "packageId":"797b8b8e659a4cdc8ffd5b94d3b3bf88",
      "type":"Axure:Master",
      "name":"顶部导航栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c72127da877f41d08da31e56aa0266c2",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"16px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":81,
                "y":15},
              "size":{
                "width":65,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c93b96ae71564872816738c89abe4513",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"16px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":81,
                    "y":15},
                  "size":{
                    "width":65,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f71e246ba6b74835860f0bfcab04f308",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"14px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":166,
                "y":15},
              "size":{
                "width":57,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e1d3de2f32394c9e989d5afc41f1587c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"14px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":166,
                    "y":15},
                  "size":{
                    "width":57,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b26caeda95384414bd106fcc1a7ba7b0",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"14px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":257,
                "y":15},
              "size":{
                "width":57,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4e51d42edeef483788a151e3688e5713",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"14px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":257,
                    "y":15},
                  "size":{
                    "width":57,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"0e2ee53199254a4580d7b6b7166ac6a0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "fill":{
                "fillType":"solid",
                "color":0xFF4092F2},
              "size":{
                "width":1028,
                "height":62},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aefc87321f774b5e9b6502bd2ebbcd78",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4092F2},
                  "size":{
                    "width":1028,
                    "height":62},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/个人中心/u4.png"}},
{
            "id":"f3fcb959b8114eb7b4e5e4b2d985b0ff",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"16px",
              "fontWeight":"200",
              "location":{
                "x":20,
                "y":5},
              "size":{
                "width":50,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF},
              "cornerRadiusTopLeft":"20"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e2fbcd33a9474661923bcaa6c76a15fa",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"16px",
                  "fontWeight":"200",
                  "location":{
                    "x":20,
                    "y":5},
                  "size":{
                    "width":50,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF},
                  "cornerRadiusTopLeft":"20"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard______/u47.png"}},
{
            "id":"f465081ff132468e97c3431164b760d8",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"18px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":87,
                "y":19},
              "size":{
                "width":37,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cd8e82fe26824574996b3e7d5cb37c98",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"18px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":87,
                    "y":19},
                  "size":{
                    "width":37,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"aeee6ed32fbd4b638572b95d5f4d9c7d",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
              "location":{
                "x":815,
                "y":3},
              "size":{
                "width":178,
                "height":35}},
            "adaptiveStyles":{
},
            "masterId":"32c07b15726d4f899752d3acce449de0"},
{
            "id":"ec989fd948b346ac9230d9bd414c56cb",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"16px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":181,
                "y":21},
              "size":{
                "width":65,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e5eabbce5a624bbc842b181206f5250c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"16px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":181,
                    "y":21},
                  "size":{
                    "width":65,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9a8b764c32c945f981cfe5bb7ade0443",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"16px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":268,
                "y":21},
              "size":{
                "width":65,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"02b4b749607f489291f72373ea4f5904",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"16px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":268,
                    "y":21},
                  "size":{
                    "width":65,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"535eec2e465246849d42dd6785c015b2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'SimSun', 'SimSun'",
              "location":{
                "x":424,
                "y":31},
              "size":{
                "width":6,
                "height":4},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"246088f1da8c4723a24f72646da0a8a4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'SimSun', 'SimSun'",
                  "location":{
                    "x":424,
                    "y":31},
                  "size":{
                    "width":6,
                    "height":4},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/申请pdb权限/u86.png"}},
{
            "id":"d66c28c6a3784f2181893c0e9fee4f3e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'SimSun', 'SimSun'",
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "location":{
                "x":424,
                "y":29},
              "size":{
                "width":6,
                "height":4},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF333333}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0844818ef5f84bea95289f455c649f54",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'SimSun', 'SimSun'",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "location":{
                    "x":424,
                    "y":29},
                  "size":{
                    "width":6,
                    "height":4},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF333333}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard______/u58.png"}},
{
            "id":"912937e4db4e4ff0bffdb4d516328395",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"16px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":355,
                "y":21},
              "size":{
                "width":65,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"37ded685bbe2413f9a0cdb3ca5bcc46f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"16px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":355,
                    "y":21},
                  "size":{
                    "width":65,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "32c07b15726d4f899752d3acce449de0":{
      "packageId":"32c07b15726d4f899752d3acce449de0",
      "type":"Axure:Master",
      "name":"用户登录信息",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d38912618fc048dd8bebd5556e358ae2",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"14px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":0,
                "y":18},
              "size":{
                "width":83,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"72bcdf779c534a7c8c3aa4e174d21f62",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"14px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":0,
                    "y":18},
                  "size":{
                    "width":83,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a6a286d3ad89432f96748b80086d8ea4",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"14px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":149,
                "y":18},
              "size":{
                "width":29,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"74c24a3ce6d142c4a516441e64393af4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"14px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":149,
                    "y":18},
                  "size":{
                    "width":29,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9845523eee044a0f9340b319cd121871",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":90,
                "y":22},
              "size":{
                "width":6,
                "height":4},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF999999}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fd3873d3efd1477fb7d4df9e5edeb942",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "location":{
                    "x":90,
                    "y":22},
                  "size":{
                    "width":6,
                    "height":4},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF999999}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard______/u56.png"}},
{
            "id":"cd4e2c1e855d473cb3bc5298653eff1b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "location":{
                "x":90,
                "y":20},
              "size":{
                "width":6,
                "height":4},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF333333}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"728a015c14be4ec0b72532cd8d44a7e6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "location":{
                    "x":90,
                    "y":20},
                  "size":{
                    "width":6,
                    "height":4},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF333333}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard______/u58.png"}},
{
            "id":"a4ada45aff0049d8b06e79ccd62b63fc",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF00CBFF},
              "location":{
                "x":74,
                "y":0},
              "size":{
                "width":21,
                "height":18},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF00CBFF},
              "cornerRadiusTopLeft":"25"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dcb224db9d1649e3b61a5d345dc19142",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF00CBFF},
                  "location":{
                    "x":74,
                    "y":0},
                  "size":{
                    "width":21,
                    "height":18},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF00CBFF},
                  "cornerRadiusTopLeft":"25"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard______/u60.png"}},
{
            "id":"c7a079868e594cdab8838b66b6f2d149",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"14px",
              "fontWeight":"200",
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":106,
                "y":17},
              "size":{
                "width":33,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"77c5935fc35b47ad91c9e296c0007fc6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"14px",
                  "fontWeight":"200",
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":106,
                    "y":17},
                  "size":{
                    "width":33,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "44edf4e907894980bb4b3423f2dd4166":{
      "packageId":"44edf4e907894980bb4b3423f2dd4166",
      "type":"Axure:Master",
      "name":"账号导航栏（MATRIX）",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fd034254c1284609b3b19c6048cff363",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF272930},
              "location":{
                "x":0,
                "y":61},
              "size":{
                "width":180,
                "height":818},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFDCE4EA}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b71095568a034363b60fa61233d12333",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF272930},
                  "location":{
                    "x":0,
                    "y":61},
                  "size":{
                    "width":180,
                    "height":818},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFDCE4EA}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard______/u1.png"}},
{
            "id":"8b67c36d21a24d11b17eda95cfb91dc8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF343740},
              "location":{
                "x":0,
                "y":69},
              "size":{
                "width":180,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f1f227617ec74444bea6f0a3c83a3797",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF343740},
                  "location":{
                    "x":0,
                    "y":69},
                  "size":{
                    "width":180,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard______/u3.png"}},
{
            "id":"d3c2aad39fb346f7908a3e034f663c1a",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"14px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1,
                "opacity":1},
              "location":{
                "x":64,
                "y":86},
              "size":{
                "width":43,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"528873bc60654604862d4984e7569285",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"14px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFA1A1A1,
                    "opacity":1},
                  "location":{
                    "x":64,
                    "y":86},
                  "size":{
                    "width":43,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2af7e4111eaf4b82bd092cf10756db8e",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"14px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF95A4B8,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF272930},
              "location":{
                "x":62,
                "y":140},
              "size":{
                "width":57,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"56d07b7569d246429a968ece7bb57e28",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"14px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF95A4B8,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF272930},
                  "location":{
                    "x":62,
                    "y":140},
                  "size":{
                    "width":57,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/个人中心/u62.png"}},
{
            "id":"8cbb6070fb7c44c2891be4fb59d810c4",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"14px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF199ED7,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF272930},
              "location":{
                "x":62,
                "y":253},
              "size":{
                "width":57,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cc832f86d0a941c1881b65eccce2b87a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"14px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF199ED7,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF272930},
                  "location":{
                    "x":62,
                    "y":253},
                  "size":{
                    "width":57,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/个人中心/u62.png"}},
{
            "id":"060afb8a78464065a9942ddb17f740ee",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF0066FF},
              "location":{
                "x":1,
                "y":69},
              "size":{
                "width":4,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"08ab20d2de684486a6479e751749b1dc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0066FF},
                  "location":{
                    "x":1,
                    "y":69},
                  "size":{
                    "width":4,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/个人中心/u64.png"}},
{
            "id":"80a655ef0685480cbf5732bccb60b42d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":34,
                "y":84},
              "size":{
                "width":18,
                "height":18}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b391fcc80c984d478365d494b05eb02d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":34,
                    "y":84},
                  "size":{
                    "width":18,
                    "height":18}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/个人中心/u66.png"}},
{
            "id":"e1440e4f0e4143b89e92e9a5778fe706",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":34,
                "y":141},
              "size":{
                "width":18,
                "height":18}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3eb55fe3b6c64ed087c1fe0fe7bba34e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":34,
                    "y":141},
                  "size":{
                    "width":18,
                    "height":18}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard______/u21.png"}},
{
            "id":"df1dee88ee3346548b04450b881e7b48",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":223},
              "size":{
                "width":180,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF363636}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/dashboard______/u29_line.png"}}]}}},
  "objectPaths":{
    "9b7fe40707c14a978bd8ced19af944f5":{
      "scriptId":"u0",
      "c72127da877f41d08da31e56aa0266c2":{
        "scriptId":"u1"},
      "c93b96ae71564872816738c89abe4513":{
        "scriptId":"u2"},
      "f71e246ba6b74835860f0bfcab04f308":{
        "scriptId":"u3"},
      "e1d3de2f32394c9e989d5afc41f1587c":{
        "scriptId":"u4"},
      "b26caeda95384414bd106fcc1a7ba7b0":{
        "scriptId":"u5"},
      "4e51d42edeef483788a151e3688e5713":{
        "scriptId":"u6"},
      "0e2ee53199254a4580d7b6b7166ac6a0":{
        "scriptId":"u7"},
      "aefc87321f774b5e9b6502bd2ebbcd78":{
        "scriptId":"u8"},
      "f3fcb959b8114eb7b4e5e4b2d985b0ff":{
        "scriptId":"u9"},
      "e2fbcd33a9474661923bcaa6c76a15fa":{
        "scriptId":"u10"},
      "f465081ff132468e97c3431164b760d8":{
        "scriptId":"u11"},
      "cd8e82fe26824574996b3e7d5cb37c98":{
        "scriptId":"u12"},
      "aeee6ed32fbd4b638572b95d5f4d9c7d":{
        "scriptId":"u13",
        "d38912618fc048dd8bebd5556e358ae2":{
          "scriptId":"u14"},
        "72bcdf779c534a7c8c3aa4e174d21f62":{
          "scriptId":"u15"},
        "a6a286d3ad89432f96748b80086d8ea4":{
          "scriptId":"u16"},
        "74c24a3ce6d142c4a516441e64393af4":{
          "scriptId":"u17"},
        "9845523eee044a0f9340b319cd121871":{
          "scriptId":"u18"},
        "fd3873d3efd1477fb7d4df9e5edeb942":{
          "scriptId":"u19"},
        "cd4e2c1e855d473cb3bc5298653eff1b":{
          "scriptId":"u20"},
        "728a015c14be4ec0b72532cd8d44a7e6":{
          "scriptId":"u21"},
        "a4ada45aff0049d8b06e79ccd62b63fc":{
          "scriptId":"u22"},
        "dcb224db9d1649e3b61a5d345dc19142":{
          "scriptId":"u23"},
        "c7a079868e594cdab8838b66b6f2d149":{
          "scriptId":"u24"},
        "77c5935fc35b47ad91c9e296c0007fc6":{
          "scriptId":"u25"}},
      "ec989fd948b346ac9230d9bd414c56cb":{
        "scriptId":"u26"},
      "e5eabbce5a624bbc842b181206f5250c":{
        "scriptId":"u27"},
      "9a8b764c32c945f981cfe5bb7ade0443":{
        "scriptId":"u28"},
      "02b4b749607f489291f72373ea4f5904":{
        "scriptId":"u29"},
      "535eec2e465246849d42dd6785c015b2":{
        "scriptId":"u30"},
      "246088f1da8c4723a24f72646da0a8a4":{
        "scriptId":"u31"},
      "d66c28c6a3784f2181893c0e9fee4f3e":{
        "scriptId":"u32"},
      "0844818ef5f84bea95289f455c649f54":{
        "scriptId":"u33"},
      "912937e4db4e4ff0bffdb4d516328395":{
        "scriptId":"u34"},
      "37ded685bbe2413f9a0cdb3ca5bcc46f":{
        "scriptId":"u35"}},
    "f148ba6665984e458e98ff9d49b485aa":{
      "scriptId":"u36"},
    "1b38e780a56040f3a0ff4da909d157a5":{
      "scriptId":"u37"},
    "09ab5ae40fda4e6fb8263494f8379c85":{
      "scriptId":"u38"},
    "716d64136acf4b1d98957636b1d68e9b":{
      "scriptId":"u39"},
    "223236c8d785428c8a8e2e8637ddbdc2":{
      "scriptId":"u40"},
    "401b56d4809e43d8b38215e245a99d2d":{
      "scriptId":"u41"},
    "a9a6ed9c841745af9b2f9f3b0cede9b2":{
      "scriptId":"u42"},
    "fa40a6d696784f32ad4e7a99f9f7156c":{
      "scriptId":"u43"},
    "621646c101904cd9adfe184322bfd9a8":{
      "scriptId":"u44"},
    "3004749a47d44c038cc6210f2a7914d3":{
      "scriptId":"u45"},
    "d321b53422db4cd5b745d84b06789168":{
      "scriptId":"u46"},
    "eb0e4b3e0fc74802afc4f76166075817":{
      "scriptId":"u47"},
    "d1565f774f024612b9be8799f57a3144":{
      "scriptId":"u48"},
    "a4191d362a9c4aaf832e4e541ec7c506":{
      "scriptId":"u49"},
    "dcbda005d35446b2b954c798a81f53c1":{
      "scriptId":"u50"},
    "dfacf743f20e4e3d8cec3983ffdbc870":{
      "scriptId":"u51"},
    "9a8260cd937043ce9daa7f47798ea39a":{
      "scriptId":"u52"},
    "410b02832c1a4570b168e974144bbea6":{
      "scriptId":"u53"},
    "749767d9a9234d8eba240b4100806d4e":{
      "scriptId":"u54"},
    "efe4cc1bbf0c405f9637ce59ac342a0a":{
      "scriptId":"u55"},
    "234cdecdcd1f43f1a8e362435d3581a8":{
      "scriptId":"u56"},
    "d0f55010de504c079a39210a7150cad7":{
      "scriptId":"u57"},
    "81331379dac843dd8ff9dcb1d95e2916":{
      "scriptId":"u58"},
    "db1d669e1d1442db891cb1cd7881742e":{
      "scriptId":"u59"},
    "3cf48c1f9ecf448c9313be18f13ed2ab":{
      "scriptId":"u60"},
    "6feeabee5c4e4488abcf17687d63ac3c":{
      "scriptId":"u61"},
    "36797feefdea4469967dfb32ad7d0a90":{
      "scriptId":"u62"},
    "f9dd59cb3bde445a93e94d56bf2ce6e8":{
      "scriptId":"u63"},
    "ca74fc71fc7a468b8f7408af1c068cf1":{
      "scriptId":"u64"},
    "af5acdf85a8e423688b2a33eb8553450":{
      "scriptId":"u65"},
    "5ede6f7a59b0470fbce309cc39dd76fc":{
      "scriptId":"u66"},
    "a246395184b7489088c3c1d297b28c3e":{
      "scriptId":"u67"},
    "a24bb366912c470f8c6528d819e148d8":{
      "scriptId":"u68"},
    "976e0b1b83744c599213fe978700309d":{
      "scriptId":"u69"},
    "ca3c27dcb0f64e788349aa849c56cc53":{
      "scriptId":"u70"},
    "e95b7cc92b014d289efee9c932f4e1ab":{
      "scriptId":"u71"},
    "f9db8e8dfb4741b98b384ae0cee15e79":{
      "scriptId":"u72"},
    "bfadcd97ebc448079de489df3992b7a0":{
      "scriptId":"u73"},
    "2caec90220394a24914649703e421266":{
      "scriptId":"u74"},
    "4c2c3e13f4734b52bd12f6ec8f311ee6":{
      "scriptId":"u75"},
    "ce894ec4218b48019b54d6d79321f47c":{
      "scriptId":"u76"},
    "3143efaae13142eca4b2ac35f4692490":{
      "scriptId":"u77"},
    "ba05bd2c03844d839f105b2ad7f2badd":{
      "scriptId":"u78"},
    "d7759c93c71e4483b88be31fe7d2c75a":{
      "scriptId":"u79"},
    "af33c6afc8a04e29bb652d785d1a8e3a":{
      "scriptId":"u80"},
    "b363982fcff74e619d997d6b9a5fdf80":{
      "scriptId":"u81"},
    "b169b5b21f6347b0bc34b8a19aa9cd48":{
      "scriptId":"u82"},
    "ce768a52ca23478089ff934247bac62f":{
      "scriptId":"u83"},
    "f3847b31087143b583ead7ee888e8dac":{
      "scriptId":"u84"},
    "9a9e8d92963a4a38b130696f62679b8a":{
      "scriptId":"u85"},
    "f1c84af07fa7499080a2a04d2b798537":{
      "scriptId":"u86"},
    "7376f30b1b8645cb9dd65687fc3db41b":{
      "scriptId":"u87"},
    "5a4b00ac5df84be3af8af2589810397e":{
      "scriptId":"u88"},
    "063b3e5511904a49807a1631fdfb9d7f":{
      "scriptId":"u89",
      "fd034254c1284609b3b19c6048cff363":{
        "scriptId":"u90"},
      "b71095568a034363b60fa61233d12333":{
        "scriptId":"u91"},
      "8b67c36d21a24d11b17eda95cfb91dc8":{
        "scriptId":"u92"},
      "f1f227617ec74444bea6f0a3c83a3797":{
        "scriptId":"u93"},
      "d3c2aad39fb346f7908a3e034f663c1a":{
        "scriptId":"u94"},
      "528873bc60654604862d4984e7569285":{
        "scriptId":"u95"},
      "2af7e4111eaf4b82bd092cf10756db8e":{
        "scriptId":"u96"},
      "56d07b7569d246429a968ece7bb57e28":{
        "scriptId":"u97"},
      "8cbb6070fb7c44c2891be4fb59d810c4":{
        "scriptId":"u98"},
      "cc832f86d0a941c1881b65eccce2b87a":{
        "scriptId":"u99"},
      "060afb8a78464065a9942ddb17f740ee":{
        "scriptId":"u100"},
      "08ab20d2de684486a6479e751749b1dc":{
        "scriptId":"u101"},
      "80a655ef0685480cbf5732bccb60b42d":{
        "scriptId":"u102"},
      "b391fcc80c984d478365d494b05eb02d":{
        "scriptId":"u103"},
      "e1440e4f0e4143b89e92e9a5778fe706":{
        "scriptId":"u104"},
      "3eb55fe3b6c64ed087c1fe0fe7bba34e":{
        "scriptId":"u105"},
      "df1dee88ee3346548b04450b881e7b48":{
        "scriptId":"u106"}}}});