$axure.loadCurrentPage({
  "url":"dashboard.html",
  "generationDate":new Date(1407727895615.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2b7ee1c91003458c8a079dbd40f9d2f8",
    "type":"Axure:Page",
    "name":"Dashboard",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"640d05bdfdf341a8a310178138944830",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20}},
          "adaptiveStyles":{
},
          "masterId":"797b8b8e659a4cdc8ffd5b94d3b3bf88"},
{
          "id":"676315b4cdf944b98d88527020fcf3b6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":197,
              "y":145},
            "size":{
              "width":848,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/dashboard______/u80_line.png"}},
{
          "id":"e81ba44cc5db45edb17e38d796efd9dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":240,
              "y":106},
            "size":{
              "width":443,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8035a6c6d8c24cb9a6071891b7355f07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":240,
                  "y":106},
                "size":{
                  "width":443,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64632c2962814e3faec36c825e8c8d69",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":198,
              "y":150},
            "size":{
              "width":848,
              "height":750},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0eb959f6fa7c4a2096e676f9ddf677e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":198,
                  "y":150},
                "size":{
                  "width":848,
                  "height":750},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard______/u74.png"}},
{
          "id":"83ecce3dd3084f69a7cab797cba080bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":180},
            "size":{
              "width":791,
              "height":670},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb5dc7ced8e644d0aee0ce6831f139a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":180},
                "size":{
                  "width":791,
                  "height":670},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u41.png"}},
{
          "id":"c668a01a8b954be29a77a609855e8060",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"center",
            "location":{
              "x":545,
              "y":210},
            "size":{
              "width":49,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"118d10f6ae5f48d6a1bcf2685a1f9d78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "location":{
                  "x":545,
                  "y":210},
                "size":{
                  "width":49,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3d7e76b024f4e738a68ff9553ffd35b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"center",
            "location":{
              "x":670,
              "y":210},
            "size":{
              "width":53,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b30823dd91644f14b5c12f854b3c8c8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "location":{
                  "x":670,
                  "y":210},
                "size":{
                  "width":53,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8c6251ecaac427a8d090f2d0cc1a43c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"center",
            "location":{
              "x":346,
              "y":210},
            "size":{
              "width":53,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb25b4f274ba4d4fb4d7f630bdc661e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "location":{
                  "x":346,
                  "y":210},
                "size":{
                  "width":53,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2fcb9341feab49b2b3de4278a53b4e43",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"center",
            "location":{
              "x":926,
              "y":210},
            "size":{
              "width":27,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eac73842ae0045e6a18322a7a05257d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "location":{
                  "x":926,
                  "y":210},
                "size":{
                  "width":27,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d6431af83c14952b2d8a60b751830cb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":258,
              "y":233},
            "size":{
              "width":730,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/dashboard/u51_line.png"}},
{
          "id":"23330e3d88ed4f78ad2f493e70114db7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":543,
              "y":260},
            "size":{
              "width":54,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afb56730b8544211947a00d8a72d01d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":543,
                  "y":260},
                "size":{
                  "width":54,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42bdcf7f15ec41f18b999525a3a683e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":682,
              "y":260},
            "size":{
              "width":30,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de9fb2762aa1496a8bfe57626a28d951",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":682,
                  "y":260},
                "size":{
                  "width":30,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a553fbae692a40249f9888923c22ca9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":274,
              "y":260},
            "size":{
              "width":193,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed62655cfd1140eab2472c48986cfc0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":274,
                  "y":260},
                "size":{
                  "width":193,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"274ba6b27e874c558c9cf648d0210368",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":258,
              "y":285},
            "size":{
              "width":730,
              "height":45},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b67866b243ee4eb19a13744b29ce8c11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":258,
                  "y":285},
                "size":{
                  "width":730,
                  "height":45},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u58.png"}},
{
          "id":"4a7f7871f0e44bc688cae337ac932741",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":541,
              "y":302},
            "size":{
              "width":54,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d75e6ad6d8dd4b23836b9c84b4e73036",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":541,
                  "y":302},
                "size":{
                  "width":54,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39ca4f12900e484db0773f453956cba6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":678,
              "y":302},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b118a66954445968bdb2e07542f244f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":678,
                  "y":302},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e795aef6d1e24c68bc6e5b82ceadf545",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":258,
              "y":369},
            "size":{
              "width":730,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/dashboard/u64_line.png"}},
{
          "id":"f87c03aaf7724f6bb9bbb5e353c0525c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":290,
              "y":300},
            "size":{
              "width":159,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44fdd146ee114602b1bd99ca45631511",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":290,
                  "y":300},
                "size":{
                  "width":159,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb9ddce4f746497380528e36803589e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "horizontalAlignment":"center",
            "location":{
              "x":797,
              "y":210},
            "size":{
              "width":40,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0093a972c8449cb91da89a45d704489",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "horizontalAlignment":"center",
                "location":{
                  "x":797,
                  "y":210},
                "size":{
                  "width":40,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03f0dc64449940b4ac27af67c70477e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":799,
              "y":260},
            "size":{
              "width":29,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6389ed59ddc9487289e477b1682b5f8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":799,
                  "y":260},
                "size":{
                  "width":29,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af0474ad8d8b4cd6adff73fc89e531d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":803,
              "y":302},
            "size":{
              "width":22,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2686a84a9ab4636bb89fee217853745",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":803,
                  "y":302},
                "size":{
                  "width":22,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6a86c5e21944ba78a0ed07f04a2fe30",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":541,
              "y":343},
            "size":{
              "width":54,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35cfcc47d44c46b3aac889af527f023f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":541,
                  "y":343},
                "size":{
                  "width":54,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"179bac61ca9e46d6813fd22e7657cac8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":678,
              "y":343},
            "size":{
              "width":37,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"461c5838335c48f3b2a9d124856c3a73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":678,
                  "y":343},
                "size":{
                  "width":37,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ea3bd1af1994994850942abf81c4040",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":282,
              "y":343},
            "size":{
              "width":177,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fe9de5d777c49c1b456128176ab5844",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":282,
                  "y":343},
                "size":{
                  "width":177,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1681eb27a91f4deeac244159189ddcbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "location":{
              "x":805,
              "y":343},
            "size":{
              "width":22,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfc99506988c4b299b1a4c5788106486",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "location":{
                  "x":805,
                  "y":343},
                "size":{
                  "width":22,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ccacb5d6aaf40ec96fdec2b737ad57c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":709,
              "y":400},
            "size":{
              "width":279,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"166841ac2db0423e947e45712ce18f1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":709,
                  "y":400},
                "size":{
                  "width":279,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard______/u148.png"}},
{
          "id":"a6cbc5ecabf54b8dbbcf5a1e18261340",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":910,
              "y":260},
            "size":{
              "width":59,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01bf40dd4d864abd85c32ccc900c4472",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":910,
                  "y":260},
                "size":{
                  "width":59,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"766b850c7343435a864ca55f6a87441b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":910,
              "y":302},
            "size":{
              "width":59,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8ea9bbb035e49e1ae49504afc737690",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":910,
                  "y":302},
                "size":{
                  "width":59,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61579dde6f2a4dcf96d0913a8823412a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":910,
              "y":343},
            "size":{
              "width":59,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61e4b8927ea74e0282e53816ca782685",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":910,
                  "y":343},
                "size":{
                  "width":59,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36ef6cadc8334a978c0bddde1ac23bb4",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20}},
          "adaptiveStyles":{
},
          "masterId":"44edf4e907894980bb4b3423f2dd4166"}]}},
  "masters":{
    "797b8b8e659a4cdc8ffd5b94d3b3bf88":{
      "packageId":"797b8b8e659a4cdc8ffd5b94d3b3bf88",
      "type":"Axure:Master",
      "name":"顶部导航栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c72127da877f41d08da31e56aa0266c2",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"16px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":81,
                "y":15},
              "size":{
                "width":65,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c93b96ae71564872816738c89abe4513",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"16px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":81,
                    "y":15},
                  "size":{
                    "width":65,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f71e246ba6b74835860f0bfcab04f308",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"14px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":166,
                "y":15},
              "size":{
                "width":57,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e1d3de2f32394c9e989d5afc41f1587c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"14px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":166,
                    "y":15},
                  "size":{
                    "width":57,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b26caeda95384414bd106fcc1a7ba7b0",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"14px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":257,
                "y":15},
              "size":{
                "width":57,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4e51d42edeef483788a151e3688e5713",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"14px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":257,
                    "y":15},
                  "size":{
                    "width":57,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"0e2ee53199254a4580d7b6b7166ac6a0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "fill":{
                "fillType":"solid",
                "color":0xFF4092F2},
              "size":{
                "width":1028,
                "height":62},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aefc87321f774b5e9b6502bd2ebbcd78",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF4092F2},
                  "size":{
                    "width":1028,
                    "height":62},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/个人中心/u4.png"}},
{
            "id":"f3fcb959b8114eb7b4e5e4b2d985b0ff",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"16px",
              "fontWeight":"200",
              "location":{
                "x":20,
                "y":5},
              "size":{
                "width":50,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF},
              "cornerRadiusTopLeft":"20"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e2fbcd33a9474661923bcaa6c76a15fa",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"16px",
                  "fontWeight":"200",
                  "location":{
                    "x":20,
                    "y":5},
                  "size":{
                    "width":50,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF},
                  "cornerRadiusTopLeft":"20"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard______/u47.png"}},
{
            "id":"f465081ff132468e97c3431164b760d8",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"18px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":87,
                "y":19},
              "size":{
                "width":37,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cd8e82fe26824574996b3e7d5cb37c98",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"18px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":87,
                    "y":19},
                  "size":{
                    "width":37,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"aeee6ed32fbd4b638572b95d5f4d9c7d",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
              "location":{
                "x":815,
                "y":3},
              "size":{
                "width":178,
                "height":35}},
            "adaptiveStyles":{
},
            "masterId":"32c07b15726d4f899752d3acce449de0"},
{
            "id":"ec989fd948b346ac9230d9bd414c56cb",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"16px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":181,
                "y":21},
              "size":{
                "width":65,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e5eabbce5a624bbc842b181206f5250c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"16px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":181,
                    "y":21},
                  "size":{
                    "width":65,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9a8b764c32c945f981cfe5bb7ade0443",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"16px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":268,
                "y":21},
              "size":{
                "width":65,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"02b4b749607f489291f72373ea4f5904",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"16px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":268,
                    "y":21},
                  "size":{
                    "width":65,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"535eec2e465246849d42dd6785c015b2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'SimSun', 'SimSun'",
              "location":{
                "x":424,
                "y":31},
              "size":{
                "width":6,
                "height":4},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"246088f1da8c4723a24f72646da0a8a4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'SimSun', 'SimSun'",
                  "location":{
                    "x":424,
                    "y":31},
                  "size":{
                    "width":6,
                    "height":4},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/申请pdb权限/u86.png"}},
{
            "id":"d66c28c6a3784f2181893c0e9fee4f3e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'SimSun', 'SimSun'",
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "location":{
                "x":424,
                "y":29},
              "size":{
                "width":6,
                "height":4},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF333333}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0844818ef5f84bea95289f455c649f54",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'SimSun', 'SimSun'",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "location":{
                    "x":424,
                    "y":29},
                  "size":{
                    "width":6,
                    "height":4},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF333333}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard______/u58.png"}},
{
            "id":"912937e4db4e4ff0bffdb4d516328395",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"16px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":355,
                "y":21},
              "size":{
                "width":65,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"37ded685bbe2413f9a0cdb3ca5bcc46f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"16px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":355,
                    "y":21},
                  "size":{
                    "width":65,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "32c07b15726d4f899752d3acce449de0":{
      "packageId":"32c07b15726d4f899752d3acce449de0",
      "type":"Axure:Master",
      "name":"用户登录信息",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d38912618fc048dd8bebd5556e358ae2",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"14px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":0,
                "y":18},
              "size":{
                "width":83,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"72bcdf779c534a7c8c3aa4e174d21f62",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"14px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":0,
                    "y":18},
                  "size":{
                    "width":83,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a6a286d3ad89432f96748b80086d8ea4",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"14px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":149,
                "y":18},
              "size":{
                "width":29,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"74c24a3ce6d142c4a516441e64393af4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"14px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":149,
                    "y":18},
                  "size":{
                    "width":29,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9845523eee044a0f9340b319cd121871",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF999999},
              "location":{
                "x":90,
                "y":22},
              "size":{
                "width":6,
                "height":4},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF999999}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fd3873d3efd1477fb7d4df9e5edeb942",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF999999},
                  "location":{
                    "x":90,
                    "y":22},
                  "size":{
                    "width":6,
                    "height":4},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF999999}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard______/u56.png"}},
{
            "id":"cd4e2c1e855d473cb3bc5298653eff1b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "location":{
                "x":90,
                "y":20},
              "size":{
                "width":6,
                "height":4},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF333333}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"728a015c14be4ec0b72532cd8d44a7e6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "location":{
                    "x":90,
                    "y":20},
                  "size":{
                    "width":6,
                    "height":4},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF333333}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard______/u58.png"}},
{
            "id":"a4ada45aff0049d8b06e79ccd62b63fc",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"10px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF00CBFF},
              "location":{
                "x":74,
                "y":0},
              "size":{
                "width":21,
                "height":18},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF00CBFF},
              "cornerRadiusTopLeft":"25"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dcb224db9d1649e3b61a5d345dc19142",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"10px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF00CBFF},
                  "location":{
                    "x":74,
                    "y":0},
                  "size":{
                    "width":21,
                    "height":18},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF00CBFF},
                  "cornerRadiusTopLeft":"25"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard______/u60.png"}},
{
            "id":"c7a079868e594cdab8838b66b6f2d149",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"14px",
              "fontWeight":"200",
              "underline":true,
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":106,
                "y":17},
              "size":{
                "width":33,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"77c5935fc35b47ad91c9e296c0007fc6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"14px",
                  "fontWeight":"200",
                  "underline":true,
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":106,
                    "y":17},
                  "size":{
                    "width":33,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "44edf4e907894980bb4b3423f2dd4166":{
      "packageId":"44edf4e907894980bb4b3423f2dd4166",
      "type":"Axure:Master",
      "name":"账号导航栏（MATRIX）",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fd034254c1284609b3b19c6048cff363",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF272930},
              "location":{
                "x":0,
                "y":61},
              "size":{
                "width":180,
                "height":818},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFDCE4EA}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b71095568a034363b60fa61233d12333",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF272930},
                  "location":{
                    "x":0,
                    "y":61},
                  "size":{
                    "width":180,
                    "height":818},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFDCE4EA}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard______/u1.png"}},
{
            "id":"8b67c36d21a24d11b17eda95cfb91dc8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF343740},
              "location":{
                "x":0,
                "y":69},
              "size":{
                "width":180,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f1f227617ec74444bea6f0a3c83a3797",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF343740},
                  "location":{
                    "x":0,
                    "y":69},
                  "size":{
                    "width":180,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard______/u3.png"}},
{
            "id":"d3c2aad39fb346f7908a3e034f663c1a",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"14px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFA1A1A1,
                "opacity":1},
              "location":{
                "x":64,
                "y":86},
              "size":{
                "width":43,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"528873bc60654604862d4984e7569285",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"14px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFA1A1A1,
                    "opacity":1},
                  "location":{
                    "x":64,
                    "y":86},
                  "size":{
                    "width":43,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2af7e4111eaf4b82bd092cf10756db8e",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"14px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF95A4B8,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF272930},
              "location":{
                "x":62,
                "y":140},
              "size":{
                "width":57,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"56d07b7569d246429a968ece7bb57e28",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"14px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF95A4B8,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF272930},
                  "location":{
                    "x":62,
                    "y":140},
                  "size":{
                    "width":57,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/个人中心/u62.png"}},
{
            "id":"8cbb6070fb7c44c2891be4fb59d810c4",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
              "fontSize":"14px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF199ED7,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF272930},
              "location":{
                "x":62,
                "y":253},
              "size":{
                "width":57,
                "height":14}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cc832f86d0a941c1881b65eccce2b87a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                  "fontSize":"14px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF199ED7,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF272930},
                  "location":{
                    "x":62,
                    "y":253},
                  "size":{
                    "width":57,
                    "height":14}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/个人中心/u62.png"}},
{
            "id":"060afb8a78464065a9942ddb17f740ee",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF0066FF},
              "location":{
                "x":1,
                "y":69},
              "size":{
                "width":4,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"08ab20d2de684486a6479e751749b1dc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0066FF},
                  "location":{
                    "x":1,
                    "y":69},
                  "size":{
                    "width":4,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/个人中心/u64.png"}},
{
            "id":"80a655ef0685480cbf5732bccb60b42d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":34,
                "y":84},
              "size":{
                "width":18,
                "height":18}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b391fcc80c984d478365d494b05eb02d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":34,
                    "y":84},
                  "size":{
                    "width":18,
                    "height":18}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/个人中心/u66.png"}},
{
            "id":"e1440e4f0e4143b89e92e9a5778fe706",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":34,
                "y":141},
              "size":{
                "width":18,
                "height":18}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3eb55fe3b6c64ed087c1fe0fe7bba34e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":34,
                    "y":141},
                  "size":{
                    "width":18,
                    "height":18}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard______/u21.png"}},
{
            "id":"df1dee88ee3346548b04450b881e7b48",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":223},
              "size":{
                "width":180,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF363636}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/dashboard______/u29_line.png"}}]}}},
  "objectPaths":{
    "640d05bdfdf341a8a310178138944830":{
      "scriptId":"u0",
      "c72127da877f41d08da31e56aa0266c2":{
        "scriptId":"u1"},
      "c93b96ae71564872816738c89abe4513":{
        "scriptId":"u2"},
      "f71e246ba6b74835860f0bfcab04f308":{
        "scriptId":"u3"},
      "e1d3de2f32394c9e989d5afc41f1587c":{
        "scriptId":"u4"},
      "b26caeda95384414bd106fcc1a7ba7b0":{
        "scriptId":"u5"},
      "4e51d42edeef483788a151e3688e5713":{
        "scriptId":"u6"},
      "0e2ee53199254a4580d7b6b7166ac6a0":{
        "scriptId":"u7"},
      "aefc87321f774b5e9b6502bd2ebbcd78":{
        "scriptId":"u8"},
      "f3fcb959b8114eb7b4e5e4b2d985b0ff":{
        "scriptId":"u9"},
      "e2fbcd33a9474661923bcaa6c76a15fa":{
        "scriptId":"u10"},
      "f465081ff132468e97c3431164b760d8":{
        "scriptId":"u11"},
      "cd8e82fe26824574996b3e7d5cb37c98":{
        "scriptId":"u12"},
      "aeee6ed32fbd4b638572b95d5f4d9c7d":{
        "scriptId":"u13",
        "d38912618fc048dd8bebd5556e358ae2":{
          "scriptId":"u14"},
        "72bcdf779c534a7c8c3aa4e174d21f62":{
          "scriptId":"u15"},
        "a6a286d3ad89432f96748b80086d8ea4":{
          "scriptId":"u16"},
        "74c24a3ce6d142c4a516441e64393af4":{
          "scriptId":"u17"},
        "9845523eee044a0f9340b319cd121871":{
          "scriptId":"u18"},
        "fd3873d3efd1477fb7d4df9e5edeb942":{
          "scriptId":"u19"},
        "cd4e2c1e855d473cb3bc5298653eff1b":{
          "scriptId":"u20"},
        "728a015c14be4ec0b72532cd8d44a7e6":{
          "scriptId":"u21"},
        "a4ada45aff0049d8b06e79ccd62b63fc":{
          "scriptId":"u22"},
        "dcb224db9d1649e3b61a5d345dc19142":{
          "scriptId":"u23"},
        "c7a079868e594cdab8838b66b6f2d149":{
          "scriptId":"u24"},
        "77c5935fc35b47ad91c9e296c0007fc6":{
          "scriptId":"u25"}},
      "ec989fd948b346ac9230d9bd414c56cb":{
        "scriptId":"u26"},
      "e5eabbce5a624bbc842b181206f5250c":{
        "scriptId":"u27"},
      "9a8b764c32c945f981cfe5bb7ade0443":{
        "scriptId":"u28"},
      "02b4b749607f489291f72373ea4f5904":{
        "scriptId":"u29"},
      "535eec2e465246849d42dd6785c015b2":{
        "scriptId":"u30"},
      "246088f1da8c4723a24f72646da0a8a4":{
        "scriptId":"u31"},
      "d66c28c6a3784f2181893c0e9fee4f3e":{
        "scriptId":"u32"},
      "0844818ef5f84bea95289f455c649f54":{
        "scriptId":"u33"},
      "912937e4db4e4ff0bffdb4d516328395":{
        "scriptId":"u34"},
      "37ded685bbe2413f9a0cdb3ca5bcc46f":{
        "scriptId":"u35"}},
    "676315b4cdf944b98d88527020fcf3b6":{
      "scriptId":"u36"},
    "e81ba44cc5db45edb17e38d796efd9dc":{
      "scriptId":"u37"},
    "8035a6c6d8c24cb9a6071891b7355f07":{
      "scriptId":"u38"},
    "64632c2962814e3faec36c825e8c8d69":{
      "scriptId":"u39"},
    "0eb959f6fa7c4a2096e676f9ddf677e6":{
      "scriptId":"u40"},
    "83ecce3dd3084f69a7cab797cba080bc":{
      "scriptId":"u41"},
    "fb5dc7ced8e644d0aee0ce6831f139a1":{
      "scriptId":"u42"},
    "c668a01a8b954be29a77a609855e8060":{
      "scriptId":"u43"},
    "118d10f6ae5f48d6a1bcf2685a1f9d78":{
      "scriptId":"u44"},
    "d3d7e76b024f4e738a68ff9553ffd35b":{
      "scriptId":"u45"},
    "b30823dd91644f14b5c12f854b3c8c8f":{
      "scriptId":"u46"},
    "d8c6251ecaac427a8d090f2d0cc1a43c":{
      "scriptId":"u47"},
    "cb25b4f274ba4d4fb4d7f630bdc661e7":{
      "scriptId":"u48"},
    "2fcb9341feab49b2b3de4278a53b4e43":{
      "scriptId":"u49"},
    "eac73842ae0045e6a18322a7a05257d0":{
      "scriptId":"u50"},
    "4d6431af83c14952b2d8a60b751830cb":{
      "scriptId":"u51"},
    "23330e3d88ed4f78ad2f493e70114db7":{
      "scriptId":"u52"},
    "afb56730b8544211947a00d8a72d01d4":{
      "scriptId":"u53"},
    "42bdcf7f15ec41f18b999525a3a683e9":{
      "scriptId":"u54"},
    "de9fb2762aa1496a8bfe57626a28d951":{
      "scriptId":"u55"},
    "a553fbae692a40249f9888923c22ca9f":{
      "scriptId":"u56"},
    "ed62655cfd1140eab2472c48986cfc0c":{
      "scriptId":"u57"},
    "274ba6b27e874c558c9cf648d0210368":{
      "scriptId":"u58"},
    "b67866b243ee4eb19a13744b29ce8c11":{
      "scriptId":"u59"},
    "4a7f7871f0e44bc688cae337ac932741":{
      "scriptId":"u60"},
    "d75e6ad6d8dd4b23836b9c84b4e73036":{
      "scriptId":"u61"},
    "39ca4f12900e484db0773f453956cba6":{
      "scriptId":"u62"},
    "0b118a66954445968bdb2e07542f244f":{
      "scriptId":"u63"},
    "e795aef6d1e24c68bc6e5b82ceadf545":{
      "scriptId":"u64"},
    "f87c03aaf7724f6bb9bbb5e353c0525c":{
      "scriptId":"u65"},
    "44fdd146ee114602b1bd99ca45631511":{
      "scriptId":"u66"},
    "eb9ddce4f746497380528e36803589e6":{
      "scriptId":"u67"},
    "b0093a972c8449cb91da89a45d704489":{
      "scriptId":"u68"},
    "03f0dc64449940b4ac27af67c70477e9":{
      "scriptId":"u69"},
    "6389ed59ddc9487289e477b1682b5f8b":{
      "scriptId":"u70"},
    "af0474ad8d8b4cd6adff73fc89e531d4":{
      "scriptId":"u71"},
    "e2686a84a9ab4636bb89fee217853745":{
      "scriptId":"u72"},
    "c6a86c5e21944ba78a0ed07f04a2fe30":{
      "scriptId":"u73"},
    "35cfcc47d44c46b3aac889af527f023f":{
      "scriptId":"u74"},
    "179bac61ca9e46d6813fd22e7657cac8":{
      "scriptId":"u75"},
    "461c5838335c48f3b2a9d124856c3a73":{
      "scriptId":"u76"},
    "0ea3bd1af1994994850942abf81c4040":{
      "scriptId":"u77"},
    "0fe9de5d777c49c1b456128176ab5844":{
      "scriptId":"u78"},
    "1681eb27a91f4deeac244159189ddcbe":{
      "scriptId":"u79"},
    "cfc99506988c4b299b1a4c5788106486":{
      "scriptId":"u80"},
    "9ccacb5d6aaf40ec96fdec2b737ad57c":{
      "scriptId":"u81"},
    "166841ac2db0423e947e45712ce18f1d":{
      "scriptId":"u82"},
    "a6cbc5ecabf54b8dbbcf5a1e18261340":{
      "scriptId":"u83"},
    "01bf40dd4d864abd85c32ccc900c4472":{
      "scriptId":"u84"},
    "766b850c7343435a864ca55f6a87441b":{
      "scriptId":"u85"},
    "d8ea9bbb035e49e1ae49504afc737690":{
      "scriptId":"u86"},
    "61579dde6f2a4dcf96d0913a8823412a":{
      "scriptId":"u87"},
    "61e4b8927ea74e0282e53816ca782685":{
      "scriptId":"u88"},
    "36ef6cadc8334a978c0bddde1ac23bb4":{
      "scriptId":"u89",
      "fd034254c1284609b3b19c6048cff363":{
        "scriptId":"u90"},
      "b71095568a034363b60fa61233d12333":{
        "scriptId":"u91"},
      "8b67c36d21a24d11b17eda95cfb91dc8":{
        "scriptId":"u92"},
      "f1f227617ec74444bea6f0a3c83a3797":{
        "scriptId":"u93"},
      "d3c2aad39fb346f7908a3e034f663c1a":{
        "scriptId":"u94"},
      "528873bc60654604862d4984e7569285":{
        "scriptId":"u95"},
      "2af7e4111eaf4b82bd092cf10756db8e":{
        "scriptId":"u96"},
      "56d07b7569d246429a968ece7bb57e28":{
        "scriptId":"u97"},
      "8cbb6070fb7c44c2891be4fb59d810c4":{
        "scriptId":"u98"},
      "cc832f86d0a941c1881b65eccce2b87a":{
        "scriptId":"u99"},
      "060afb8a78464065a9942ddb17f740ee":{
        "scriptId":"u100"},
      "08ab20d2de684486a6479e751749b1dc":{
        "scriptId":"u101"},
      "80a655ef0685480cbf5732bccb60b42d":{
        "scriptId":"u102"},
      "b391fcc80c984d478365d494b05eb02d":{
        "scriptId":"u103"},
      "e1440e4f0e4143b89e92e9a5778fe706":{
        "scriptId":"u104"},
      "3eb55fe3b6c64ed087c1fe0fe7bba34e":{
        "scriptId":"u105"},
      "df1dee88ee3346548b04450b881e7b48":{
        "scriptId":"u106"}}}});