$axure.loadCurrentPage({
  "url":"首页.html",
  "generationDate":new Date(1407753060078.86),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bda9f316ec9c48bcbb960ee308b70b80",
    "type":"Axure:Page",
    "name":"首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"adcba967731e45e4b66ad465538b9090",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-15,
              "y":1},
            "size":{
              "width":1439,
              "height":3369}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3134f6236a64b489c88ad457d30c4da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-15,
                  "y":1},
                "size":{
                  "width":1439,
                  "height":3369}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "adcba967731e45e4b66ad465538b9090":{
      "scriptId":"u0"},
    "e3134f6236a64b489c88ad457d30c4da":{
      "scriptId":"u1"}}});