$axure.loadCurrentPage({
  "url":"首页.html",
  "generationDate":new Date(1407753540279.58),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bda9f316ec9c48bcbb960ee308b70b80",
    "type":"Axure:Page",
    "name":"首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e15a4639ed2d48eeb045c3e6f87c0d36",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1440,
              "height":3371}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c630d436107428386fadc96ab3a1e0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1440,
                  "height":3371}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "e15a4639ed2d48eeb045c3e6f87c0d36":{
      "scriptId":"u0"},
    "1c630d436107428386fadc96ab3a1e0d":{
      "scriptId":"u1"}}});