$axure.loadCurrentPage({
  "url":"注释说明.html",
  "generationDate":new Date(1407727856215.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4a259002d0b24adb844b3ffac3e81734",
    "type":"Axure:Page",
    "name":"注释说明",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b85af117f6d84343a704d75a6119ef2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x3D0099FF},
            "location":{
              "x":0,
              "y":40},
            "size":{
              "width":1000,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4c9e81288954b399799f0ba5ac644f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x3D0099FF},
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":1000,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注释说明/u0.png"}},
{
          "id":"38be8fdba587435a85fa9dc3d583b02a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"18px",
            "fontWeight":"200",
            "location":{
              "x":16,
              "y":11},
            "size":{
              "width":91,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da2be89b8bb647d8b03f8d5a89201f3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"18px",
                "fontWeight":"200",
                "location":{
                  "x":16,
                  "y":11},
                "size":{
                  "width":91,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3df42378f48348c68f983a3963ea56c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":873,
              "y":15},
            "size":{
              "width":127,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67c12ec5e3af42af834489e0b02df7b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":873,
                  "y":15},
                "size":{
                  "width":127,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc324f8759654c388808a7db01c90d3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":50,
              "y":116},
            "size":{
              "width":57,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70d5ddec36f44a52b79e08ff854ad543",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":50,
                  "y":116},
                "size":{
                  "width":57,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64ca953c127d467eab7400b5360bb96f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":119},
            "size":{
              "width":200,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009900}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/注释说明/u8_end.png",
            "line~":"images/注释说明/u8_line.png"}},
{
          "id":"46a1342975b644d799d56b9657cf735c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":50,
              "y":169},
            "size":{
              "width":85,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bca0fa6537fc4d1c98c188d9f2043a93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":50,
                  "y":169},
                "size":{
                  "width":85,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b73d46b35f704cf88759b9eecba98872",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":168},
            "size":{
              "width":200,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0033}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/注释说明/u11_line.png"}},
{
          "id":"0a03c5523df8483a8103af95eceb8549",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":190,
              "y":168},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0033}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ad21e339d6148bea103473fe2f3804b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":190,
                  "y":168},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0033}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注释说明/u12.png"}},
{
          "id":"9cbad796750649e3a09c43e5e850cfc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":380,
              "y":168},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0033}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"826fb3ece70f46619dad01d44996ec06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":380,
                  "y":168},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0033}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注释说明/u12.png"}},
{
          "id":"9cbdb64685394902bfef72660dcf7f6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x1EFF9900},
            "location":{
              "x":190,
              "y":224},
            "size":{
              "width":20,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0x99FFCC33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3f8d4d5302d4b9194ca7be4e6375ea5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x1EFF9900},
                "location":{
                  "x":190,
                  "y":224},
                "size":{
                  "width":20,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x99FFCC33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注释说明/u16.png"}},
{
          "id":"9f175ceb7c75412dbfab1d2abb979f36",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":194,
              "y":228},
            "size":{
              "width":12,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b259ff91483a4ce68c120f863c0f9e19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":194,
                  "y":228},
                "size":{
                  "width":12,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注释说明/u18.png"}},
{
          "id":"dcd4de9f4279444ab861c2b21a9a52d1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":201,
              "y":228},
            "size":{
              "width":189,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9933}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/注释说明/u20_line.png"}},
{
          "id":"910fc5c875994a8db6e993153b5c9c22",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":50,
              "y":224},
            "size":{
              "width":71,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f50424559fd4789baf9334ec8d04860",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":50,
                  "y":224},
                "size":{
                  "width":71,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e895f176c6ca4a26b18230ca14080964",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":50,
              "y":280},
            "size":{
              "width":85,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed1e5999c38a44ae9371444950f8e3dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":50,
                  "y":280},
                "size":{
                  "width":85,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6071d896f7b40ad82d6b975d8a13d91",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":190,
              "y":286},
            "size":{
              "width":200,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5099094058924c9eaeea46a2ddef6ff4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":190,
                  "y":286},
                "size":{
                  "width":200,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注释说明/u25.png"}},
{
          "id":"a24e3f656c0c4854beb29845afc34749",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":50,
              "y":420},
            "size":{
              "width":60,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a58258fec39f4d95b3ea5ca40d760d27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":50,
                  "y":420},
                "size":{
                  "width":60,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"501f698501a14c14bc8444e547e80b3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":190,
              "y":426},
            "size":{
              "width":200,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c203c5748b024575857f1b853c3c8934",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":190,
                  "y":426},
                "size":{
                  "width":200,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注释说明/u29.png"}},
{
          "id":"9c79191376f5430a8b8867e0f7507dae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":190,
              "y":411},
            "size":{
              "width":60,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cc6f841c5f4433cb44c275bb87ae552",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":190,
                  "y":411},
                "size":{
                  "width":60,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注释说明/u31.png"}},
{
          "id":"07764aefaf3d4b52ba41907070ef9411",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":540,
              "y":116},
            "size":{
              "width":57,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"849d5724db134dc6aa2d82315e5477fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":540,
                  "y":116},
                "size":{
                  "width":57,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d302c3df662d4bdb827ff15fd7beba3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":540,
              "y":166},
            "size":{
              "width":57,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28058061bc124530aae642a03e614829",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":540,
                  "y":166},
                "size":{
                  "width":57,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa9d3418721e464f960f7cefb0fb864e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":658,
              "y":166},
            "size":{
              "width":34,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5412c45009a441d582121add48948353",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":658,
                  "y":166},
                "size":{
                  "width":34,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4ece602251a4468fa3467075af39758d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":628,
              "y":158},
            "size":{
              "width":20,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"827871e4b91548a189421339c61972d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":628,
                  "y":158},
                "size":{
                  "width":20,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注释说明/u39.png"}},
{
          "id":"90f05c75f8134e49b537a0183c33c69a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":628,
              "y":188},
            "size":{
              "width":200,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f44fda2c2924b37b417bb274470a4a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":628,
                  "y":188},
                "size":{
                  "width":200,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注释说明/u41.png"}},
{
          "id":"af9c162541874130a54219c21ad5a8ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0033,
              "opacity":1},
            "location":{
              "x":628,
              "y":114},
            "size":{
              "width":109,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"402c73d8539641679bb0de0315363e16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0033,
                  "opacity":1},
                "location":{
                  "x":628,
                  "y":114},
                "size":{
                  "width":109,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61d62d2ebdb048209a3b23fb42f78ca4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":540,
              "y":336},
            "size":{
              "width":57,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43c0c549ea584e53974e1101490c82c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'STHeitiSC-Light', 'Heiti SC Light', 'Heiti SC'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":540,
                  "y":336},
                "size":{
                  "width":57,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8b5068bd75342a9bbed256940ca1bb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":628,
              "y":351},
            "size":{
              "width":200,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54d475810b4d4f2db4d0a17f2d655230",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":628,
                  "y":351},
                "size":{
                  "width":200,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注释说明/u47.png"}},
{
          "id":"63af05b4df314da6acc6e8ffd79ed703",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":628,
              "y":336},
            "size":{
              "width":60,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6dd4c56989148c3a159c2d14520f5e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":628,
                  "y":336},
                "size":{
                  "width":60,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注释说明/u49.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "b85af117f6d84343a704d75a6119ef2c":{
      "scriptId":"u0"},
    "e4c9e81288954b399799f0ba5ac644f4":{
      "scriptId":"u1"},
    "38be8fdba587435a85fa9dc3d583b02a":{
      "scriptId":"u2"},
    "da2be89b8bb647d8b03f8d5a89201f3f":{
      "scriptId":"u3"},
    "3df42378f48348c68f983a3963ea56c4":{
      "scriptId":"u4"},
    "67c12ec5e3af42af834489e0b02df7b4":{
      "scriptId":"u5"},
    "dc324f8759654c388808a7db01c90d3f":{
      "scriptId":"u6"},
    "70d5ddec36f44a52b79e08ff854ad543":{
      "scriptId":"u7"},
    "64ca953c127d467eab7400b5360bb96f":{
      "scriptId":"u8"},
    "46a1342975b644d799d56b9657cf735c":{
      "scriptId":"u9"},
    "bca0fa6537fc4d1c98c188d9f2043a93":{
      "scriptId":"u10"},
    "b73d46b35f704cf88759b9eecba98872":{
      "scriptId":"u11"},
    "0a03c5523df8483a8103af95eceb8549":{
      "scriptId":"u12"},
    "3ad21e339d6148bea103473fe2f3804b":{
      "scriptId":"u13"},
    "9cbad796750649e3a09c43e5e850cfc1":{
      "scriptId":"u14"},
    "826fb3ece70f46619dad01d44996ec06":{
      "scriptId":"u15"},
    "9cbdb64685394902bfef72660dcf7f6a":{
      "scriptId":"u16"},
    "c3f8d4d5302d4b9194ca7be4e6375ea5":{
      "scriptId":"u17"},
    "9f175ceb7c75412dbfab1d2abb979f36":{
      "scriptId":"u18"},
    "b259ff91483a4ce68c120f863c0f9e19":{
      "scriptId":"u19"},
    "dcd4de9f4279444ab861c2b21a9a52d1":{
      "scriptId":"u20"},
    "910fc5c875994a8db6e993153b5c9c22":{
      "scriptId":"u21"},
    "0f50424559fd4789baf9334ec8d04860":{
      "scriptId":"u22"},
    "e895f176c6ca4a26b18230ca14080964":{
      "scriptId":"u23"},
    "ed1e5999c38a44ae9371444950f8e3dd":{
      "scriptId":"u24"},
    "b6071d896f7b40ad82d6b975d8a13d91":{
      "scriptId":"u25"},
    "5099094058924c9eaeea46a2ddef6ff4":{
      "scriptId":"u26"},
    "a24e3f656c0c4854beb29845afc34749":{
      "scriptId":"u27"},
    "a58258fec39f4d95b3ea5ca40d760d27":{
      "scriptId":"u28"},
    "501f698501a14c14bc8444e547e80b3c":{
      "scriptId":"u29"},
    "c203c5748b024575857f1b853c3c8934":{
      "scriptId":"u30"},
    "9c79191376f5430a8b8867e0f7507dae":{
      "scriptId":"u31"},
    "4cc6f841c5f4433cb44c275bb87ae552":{
      "scriptId":"u32"},
    "07764aefaf3d4b52ba41907070ef9411":{
      "scriptId":"u33"},
    "849d5724db134dc6aa2d82315e5477fa":{
      "scriptId":"u34"},
    "d302c3df662d4bdb827ff15fd7beba3c":{
      "scriptId":"u35"},
    "28058061bc124530aae642a03e614829":{
      "scriptId":"u36"},
    "aa9d3418721e464f960f7cefb0fb864e":{
      "scriptId":"u37"},
    "5412c45009a441d582121add48948353":{
      "scriptId":"u38"},
    "4ece602251a4468fa3467075af39758d":{
      "scriptId":"u39"},
    "827871e4b91548a189421339c61972d7":{
      "scriptId":"u40"},
    "90f05c75f8134e49b537a0183c33c69a":{
      "scriptId":"u41"},
    "9f44fda2c2924b37b417bb274470a4a2":{
      "scriptId":"u42"},
    "af9c162541874130a54219c21ad5a8ec":{
      "scriptId":"u43"},
    "402c73d8539641679bb0de0315363e16":{
      "scriptId":"u44"},
    "61d62d2ebdb048209a3b23fb42f78ca4":{
      "scriptId":"u45"},
    "43c0c549ea584e53974e1101490c82c0":{
      "scriptId":"u46"},
    "e8b5068bd75342a9bbed256940ca1bb8":{
      "scriptId":"u47"},
    "54d475810b4d4f2db4d0a17f2d655230":{
      "scriptId":"u48"},
    "63af05b4df314da6acc6e8ffd79ed703":{
      "scriptId":"u49"},
    "d6dd4c56989148c3a159c2d14520f5e4":{
      "scriptId":"u50"}}});